development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://faye-enigmates.herokuapp.com/faye"
  secret_token: "enigmates"
  signature_expiration: 86400 # one hour
