puzzle = Puzzle.create(
  name: "States in the United States",
  topic: "geography",
  format: "map")

puzzle.pieces.create([ 
  {:content=>"alabama"}, 
  {:content=>"alaska"}, 
  {:content=>"arizona"}, 
  {:content=>"arkansas"}, 
  {:content=>"california"}, 
  {:content=>"colorado"}, 
  {:content=>"connecticut"}, 
  {:content=>"delaware"}, 
  {:content=>"florida"}, 
  {:content=>"georgia"}, 
  {:content=>"hawaii"}, 
  {:content=>"idaho"}, 
  {:content=>"illinois"}, 
  {:content=>"indiana"}, 
  {:content=>"iowa"}, 
  {:content=>"kansas"}, 
  {:content=>"kentucky"}, 
  {:content=>"louisiana"}, 
  {:content=>"maine"}, 
  {:content=>"maryland"}, 
  {:content=>"massachusetts"}, 
  {:content=>"michigan"}, 
  {:content=>"minnesota"}, 
  {:content=>"mississippi"}, 
  {:content=>"missouri"}, 
  {:content=>"montana"}, 
  {:content=>"nebraska"}, 
  {:content=>"nevada"}, 
  {:content=>"new hampshire"}, 
  {:content=>"new jersey"}, 
  {:content=>"new mexico"}, 
  {:content=>"new york"}, 
  {:content=>"north carolina"}, 
  {:content=>"north dakota"}, 
  {:content=>"ohio"}, 
  {:content=>"oklahoma"}, 
  {:content=>"oregon"}, 
  {:content=>"pennsylvania"}, 
  {:content=>"rhode island"}, 
  {:content=>"south carolina"}, 
  {:content=>"south dakota"}, 
  {:content=>"tennessee"}, 
  {:content=>"texas"}, 
  {:content=>"utah"}, 
  {:content=>"vermont"}, 
  {:content=>"virginia"}, 
  {:content=>"washington"}, 
  {:content=>"west virginia"}, 
  {:content=>"wisconsin"}, 
  {:content=>"wyoming"}
])

