puzzle = Puzzle.create(
  name: "States in the United States",
  topic: "geography",
  format: "map",
  content_noun: "state",
  image_url: "states.jpg")

puzzle.pieces.create([ 
  {content: "alabama"}, 
  {content: "alaska"}, 
  {content: "arizona"}, 
  {content: "arkansas"}, 
  {content: "california"}, 
  {content: "colorado"}, 
  {content: "connecticut"}, 
  {content: "delaware"}, 
  {content: "florida"}, 
  {content: "georgia"}, 
  {content: "hawaii"}, 
  {content: "idaho"}, 
  {content: "illinois"}, 
  {content: "indiana"}, 
  {content: "iowa"}, 
  {content: "kansas"}, 
  {content: "kentucky"}, 
  {content: "louisiana"}, 
  {content: "maine"}, 
  {content: "maryland"}, 
  {content: "massachusetts"}, 
  {content: "michigan"}, 
  {content: "minnesota"}, 
  {content: "mississippi"}, 
  {content: "missouri"}, 
  {content: "montana"}, 
  {content: "nebraska"}, 
  {content: "nevada"}, 
  {content: "new hampshire"}, 
  {content: "new jersey"}, 
  {content: "new mexico"}, 
  {content: "new york"}, 
  {content: "north carolina"}, 
  {content: "north dakota"}, 
  {content: "ohio"}, 
  {content: "oklahoma"}, 
  {content: "oregon"}, 
  {content: "pennsylvania"}, 
  {content: "rhode island"}, 
  {content: "south carolina"}, 
  {content: "south dakota"}, 
  {content: "tennessee"}, 
  {content: "texas"}, 
  {content: "utah"}, 
  {content: "vermont"}, 
  {content: "virginia"}, 
  {content: "washington"}, 
  {content: "west virginia"}, 
  {content: "wisconsin"}, 
  {content: "wyoming"}
])

puzzle2 = Puzzle.create(
  name: "Best Picture Oscar Winners of Last 25 Years",
  topic: "culture",
  format: "list",
  hint_noun: "year",
  content_noun: "movie",
  image_url: "oscars.jpg")

puzzle2.pieces.create([ 
  {content: "argo", hint: "2012"}, 
  {content: "the artist", hint: "2011"}, 
  {content: "the king's speech", hint: "2010"},
  {content: "the hurt locker", hint: "2009"},
  {content: "slumdog millionaire", hint: "2008"},
  {content: "no country for old men", hint: "2007"},
  {content: "the departed", hint: "2006"},
  {content: "crash", hint: "2005"},
  {content: "million dollar baby", hint: "2004"},
  {content: "the lord of the rings: the return of the king", hint: "2003"},
  {content: "chicago", hint: "2002"},
  {content: "a beautiful mind", hint: "2001"},
  {content: "gladiator", hint: "2000"},
  {content: "american beauty", hint: "1999"},
  {content: "shakespeare in love", hint: "1998"},
  {content: "titanic", hint: "1997"},
  {content: "the english patient", hint: "1996"},
  {content: "braveheart", hint: "1995"},
  {content: "forrest gump", hint: "1994"},
  {content: "schindler's list", hint: "1993"},
  {content: "unforgiven", hint: "1992"},
  {content: "the silence of the lambs", hint: "1991"},
  {content: "dances with wolves", hint: "1990"},
  {content: "driving miss daisy", hint: "1989"},
  {content: "rain man", hint: "1988"}
])

puzzle3 = Puzzle.create(
  name: "Record-Breaking Athletes",
  topic: "sports",
  format: "questions",
  hint_noun: "record",
  content_noun: "player",
  image_url: "sports.jpg")


